/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    
    db database = new db();
    
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        displayEmployeesData();
        displayEmployeeAttendance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        btnSignOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUpdateRecord = new javax.swing.JButton();
        lblEmployeeNo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtSSS = new javax.swing.JTextField();
        txtPhilhealth = new javax.swing.JTextField();
        txtTIN = new javax.swing.JTextField();
        txtPagibig = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new javax.swing.JTable();
        btnComputeSalary = new javax.swing.JButton();
        btnDeleteRecord = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAttendance = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnCreateRecord1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome to Motor PH");

        btnSignOut.setText("Sign Out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });

        jLabel2.setText("Last Name:");

        txtFirstName.setEditable(false);
        txtFirstName.setToolTipText("");

        jLabel4.setText("First Name:");

        jLabel3.setText("SSS No.:");

        btnUpdateRecord.setText("Update Record");
        btnUpdateRecord.setEnabled(false);
        btnUpdateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRecordActionPerformed(evt);
            }
        });

        lblEmployeeNo.setText("0000-0000");

        jLabel5.setText("Employee No:");

        jLabel6.setText("Employee Details");

        jLabel7.setText("Philhealth No.:");

        jLabel8.setText("TIN:");

        jLabel11.setText("Pagibig No.:");

        txtLastName.setEditable(false);
        txtLastName.setToolTipText("");

        txtSSS.setEditable(false);
        txtSSS.setToolTipText("");

        txtPhilhealth.setEditable(false);
        txtPhilhealth.setToolTipText("");

        txtTIN.setEditable(false);
        txtTIN.setToolTipText("");

        txtPagibig.setEditable(false);
        txtPagibig.setToolTipText("");

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmployees.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(tblEmployees);

        btnComputeSalary.setText("Compute Employee Salary");
        btnComputeSalary.setEnabled(false);
        btnComputeSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputeSalaryActionPerformed(evt);
            }
        });

        btnDeleteRecord.setText("Delete Employee");
        btnDeleteRecord.setEnabled(false);
        btnDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRecordActionPerformed(evt);
            }
        });

        tblAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAttendance);

        jLabel12.setText("Motor PH Employees:");

        jLabel13.setText("Employee <No> Attendances");

        btnCreateRecord1.setText("Create Record");
        btnCreateRecord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRecord1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnUpdateRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnComputeSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel2))
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel11)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel5))))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblEmployeeNo)
                                                .addComponent(txtPagibig, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtPhilhealth, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel1))
                                    .addComponent(btnDeleteRecord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnCreateRecord1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSignOut))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(btnSignOut))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblEmployeeNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPhilhealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPagibig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdateRecord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteRecord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateRecord1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(btnComputeSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel12)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void updateFields(boolean isEnabled) {
        txtFirstName.setEditable(isEnabled);
        txtLastName.setEditable(isEnabled);
        txtSSS.setEditable(isEnabled);
        txtPhilhealth.setEditable(isEnabled);
        txtTIN.setEditable(isEnabled);
        txtPagibig.setEditable(isEnabled);
        btnUpdateRecord.setEnabled(isEnabled);
        btnDeleteRecord.setEnabled(isEnabled);
        btnComputeSalary.setEnabled(isEnabled);
   }
   
   private void clearFields() {
        txtFirstName.setText("");
        txtLastName.setText("");
        txtSSS.setText("");
        txtPhilhealth.setText("");
        txtTIN.setText("");
        txtPagibig.setText("");
        lblEmployeeNo.setText("0000-0000");
        btnUpdateRecord.setEnabled(false);
        btnDeleteRecord.setEnabled(false);
        btnComputeSalary.setEnabled(false);
   }
    
    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        LoginForm loginForm = new LoginForm(); 
        loginForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnUpdateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRecordActionPerformed
        String lastName = txtLastName.getText();
        String firstName = txtFirstName.getText();
        String sss = txtSSS.getText();
        String philhealth = txtPhilhealth.getText();
        String tin = txtTIN.getText();
        String pagibig = txtPagibig.getText();
        String employeeNo = lblEmployeeNo.getText();

        // Call the update functionality in db.java
        boolean success = database.updateRecord(lastName, firstName, sss, philhealth, tin, pagibig, employeeNo);
        
        // Check if the update was successful
        if (success) {
            displayEmployeesData();
            clearFields();
            JOptionPane.showMessageDialog(MainForm.this, "Record updated successfully!");
        } else {
            JOptionPane.showMessageDialog(MainForm.this, "Failed to update record. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateRecordActionPerformed

    private void btnComputeSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputeSalaryActionPerformed
        Salary salary = new Salary(this, lblEmployeeNo.getText());
        salary.setVisible(true);
    }//GEN-LAST:event_btnComputeSalaryActionPerformed

    private void btnDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRecordActionPerformed
        boolean deleted = database.deleteEmployee(Integer.parseInt(lblEmployeeNo.getText()));
        if (deleted) {
            displayEmployeesData();
            clearFields();
        } else {
            // Handle deletion failure
            JOptionPane.showMessageDialog(MainForm.this, "Failed to delete employee.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteRecordActionPerformed

    private void btnCreateRecord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRecord1ActionPerformed
       
        AddEmployee test = new AddEmployee();
        test.setVisible(true);
        /* try {
        String lastEmpNo = getLastEmployeeNo();
        int newEmpNoStr = Integer.parseInt(lastEmpNo) + 1;
        String newEmpNo = String.format("%04d", newEmpNoStr);
        
        AddEmployee addNewEmp = new AddEmployee(newEmpNo); // Pass the db instance
        addNewEmp.setVisible(true);
    } catch (Exception e) {
        e.printStackTrace();
        }
    */
    }//GEN-LAST:event_btnCreateRecord1ActionPerformed
    
    private String getLastEmployeeNo() throws Exception {
        String lastEmployeeNo = "";
        
        String url = "jdbc:mysql://localhost:3306/your-database-name"; // Adjust as necessary
        String user = "your-username"; // Adjust as necessary
        String password = "your-password"; // Adjust as necessary

        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        
        try {
            // Establish the database connection
                conn = DriverManager.getConnection(url, user, password);
            // Create a statement
            stmt = conn.createStatement();
            // Execute the query
            rs = stmt.executeQuery("SELECT id FROM employees ORDER BY id DESC LIMIT 1");
            // Process the result set
            if (rs.next()) {
                lastEmployeeNo = rs.getString("id");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            throw e; // Rethrow the exception for further handling
        } finally {
            // Close resources
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if (stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
        return lastEmployeeNo;
    }
        
    private void displayEmployeesData() {
        List<Employee> employees = database.getAllEmployees();

        String[] columnNames = {"ID", "First Name", "Last Name", "SSS No.", "Philhealth No.", "TIN", "Pagibig No."};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        for (Employee emp : employees) {
            Object[] rowData = {
                emp.getId(),
                emp.getFirst_name(),
                emp.getLast_name(),
                emp.getSss(),
                emp.getPhilhealth(),
                emp.getTin(),
                emp.getPagibig(),
            };
            model.addRow(rowData);
        }
        tblEmployees.setModel(model);
        
        tblEmployees.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = tblEmployees.getSelectedRow();
                if (selectedRow != -1) {
                    updateFields(true);
                    // If a row is selected
                    DefaultTableModel model1 = (DefaultTableModel) tblEmployees.getModel();
                    // Retrieve data from the selected row
                    String employeeNo = model1.getValueAt(selectedRow, 0).toString();
                    String firstName = model1.getValueAt(selectedRow, 1).toString();
                    String lastName = model1.getValueAt(selectedRow, 2).toString();
                    String sss = model1.getValueAt(selectedRow, 3).toString();
                    String philhealth = model1.getValueAt(selectedRow, 4).toString();
                    String tin = model1.getValueAt(selectedRow, 5).toString();
                    String pagibig = model1.getValueAt(selectedRow, 6).toString();
                    // Set data to the fields
                    lblEmployeeNo.setText(employeeNo);
                    txtFirstName.setText(firstName);
                    txtLastName.setText(lastName);
                    txtSSS.setText(sss);
                    txtPhilhealth.setText(philhealth);
                    txtTIN.setText(tin);
                    txtPagibig.setText(pagibig);
                } else {
                    updateFields(false);
                }
            }
        });
    }
    
    private void displayEmployeeAttendance() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("Date");
        model.addColumn("Start Time");
        model.addColumn("End Time");

        tblAttendance.setModel(model);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComputeSalary;
    private javax.swing.JButton btnCreateRecord1;
    private javax.swing.JButton btnDeleteRecord;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JButton btnUpdateRecord;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblEmployeeNo;
    private javax.swing.JTable tblAttendance;
    private javax.swing.JTable tblEmployees;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPagibig;
    private javax.swing.JTextField txtPhilhealth;
    private javax.swing.JTextField txtSSS;
    private javax.swing.JTextField txtTIN;
    // End of variables declaration//GEN-END:variables
}
